"""
Django settings for moonbase project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os
from datetime import timedelta

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment setup
VALID_ENV_TYPES = ['local', 'docker', 'prod']
ENV_TYPE = os.getenv('ENV_TYPE', 'local')

if ENV_TYPE not in VALID_ENV_TYPES:
    raise ValueError(f"ENV_TYPE must be one of {VALID_ENV_TYPES}")

# Load environment files based on ENV_TYPE
if ENV_TYPE == 'local':
    # For local, only load local settings
    env_file = BASE_DIR / '.env.local.dev'
elif ENV_TYPE == 'docker':
    # For docker, only load docker settings
    env_file = BASE_DIR / '.env.docker.dev'
elif ENV_TYPE == 'prod':
    # For prod, only load prod settings
    env_file = BASE_DIR / '.env.prod'
else:
    raise ValueError(f"Unhandled ENV_TYPE: {ENV_TYPE}")

# Verify and load the environment file
if not env_file.exists():
    raise FileNotFoundError(
        f"Required environment file not found: {env_file}\n"
        f"This file is required for ENV_TYPE={ENV_TYPE}"
    )

# Add this line after your env_file validation
environ.Env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS').split()  # This will split on whitespace


# Application definition

INSTALLED_APPS = [
    'lab.apps.LabConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'lab.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Lab API',
    'DESCRIPTION': 'API for managing classrooms and exercises',
    'VERSION': '1.0.0',
} 

MIDDLEWARE = [
    # 'lab.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configure CORS to allow credentials
CORS_ALLOW_CREDENTIALS = True  # Important for cookies
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Add these settings if not already present
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Add this setting to determine if we're in development
IS_DEVELOPMENT = ENV_TYPE == 'local'

# JWT settings
SIMPLE_JWT = {
    # Cookie settings
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': False,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'AUTH_COOKIE_PATH': '/',
    
    # Token lifetime
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # User identification
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

LOGIN_REDIRECT_URL = 'http://localhost:3000'
LOGOUT_REDIRECT_URL = 'http://localhost:3000'

ROOT_URLCONF = 'moonbase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'moonbase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Add after your database settings
print("Current ENV_TYPE:", ENV_TYPE)
print("Database settings:")
print(f"NAME: {env('DB_NAME')}")
print(f"USER: {env('DB_USER')}")
print(f"HOST: {env('DB_HOST')}")
print(f"PORT: {env('DB_PORT')}")

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTHENTICATION_BACKENDS = [
    'lab.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
RESEND_SMTP_PORT = 587
RESEND_SMTP_USERNAME = 'resend'
RESEND_SMTP_HOST = 'smtp.resend.com'
RESEND_SMTP_PASSWORD = env('RESEND_API_KEY')

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not IS_DEVELOPMENT
CSRF_USE_SESSIONS = True

# Update Session settings
SESSION_COOKIE_SECURE = not IS_DEVELOPMENT

# Add these logging settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'lab.authentication': {
            'handlers': ['console'],
            'level': 'DEBUG',
        }
    },
}

# Security Settings for Production
if ENV_TYPE == 'prod':
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Set DEBUG to False in production
    DEBUG = False
    
    # Update JWT cookie settings for production
    SIMPLE_JWT['AUTH_COOKIE_SECURE'] = True
    SIMPLE_JWT['AUTH_COOKIE_SAMESITE'] = 'Lax'

# Make sure to generate a strong SECRET_KEY for production
if ENV_TYPE == 'prod' and (
    len(SECRET_KEY) < 50 
    or SECRET_KEY.startswith('django-insecure-')
    or len(set(SECRET_KEY)) < 5
):
    raise ValueError(
        'Production environment detected with an insecure SECRET_KEY. '
        'Please set a strong SECRET_KEY in your .env.prod file'
    )