# Generated by Django 5.0.6 on 2024-12-17 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('instructions', models.TextField()),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('test_feedback', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ClassroomExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.classrooms')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.exercises')),
            ],
            options={
                'verbose_name': 'Classroom Exercise',
                'verbose_name_plural': 'Classroom Exercises',
                'db_table': 'classroom_exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.exercises')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.tests')),
            ],
            options={
                'verbose_name': 'Exercise Test',
                'verbose_name_plural': 'Exercise Tests',
                'db_table': 'exercise_tests',
            },
        ),
        migrations.CreateModel(
            name='UserExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users')),
            ],
            options={
                'verbose_name': 'User Exercise',
                'verbose_name_plural': 'User Exercises',
                'db_table': 'user_exercises',
            },
        ),
        migrations.AddField(
            model_name='exercises',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users'),
        ),
        migrations.CreateModel(
            name='ClassroomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.classrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users')),
            ],
            options={
                'verbose_name': 'Classroom User',
                'verbose_name_plural': 'Classroom Users',
                'db_table': 'classroom_users',
            },
        ),
        migrations.AddField(
            model_name='classrooms',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users'),
        ),
    ]
