# Generated by Django 5.0.6 on 2025-01-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_submissions_delete_userexercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='test_feedback',
            new_name='expected_output',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tests',
            name='help_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tests',
            name='test_type',
            field=models.CharField(choices=[('includes', 'Output includes expected output'), ('exact', 'Output matches expected output exactly')], default='includes', max_length=20),
        ),
    ]
