# Generated by Django 5.0.6 on 2024-08-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
