# Generated by Django 5.0.6 on 2024-08-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_created_by_classrooms_creator_user_exercises_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroomexercises',
            options={'verbose_name': 'Classroom Exercise', 'verbose_name_plural': 'Classroom Exercises'},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.AlterModelOptions(
            name='classroomusers',
            options={'verbose_name': 'Classroom User', 'verbose_name_plural': 'Classroom Users'},
        ),
        migrations.AlterModelOptions(
            name='exercises',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='userexercises',
            options={'verbose_name': 'User Exercise', 'verbose_name_plural': 'User Exercises'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
