# Generated by Django 5.0.6 on 2024-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_classroomexercises_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
