# Generated by Django 5.0.6 on 2024-12-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_classrooms_slug_alter_classrooms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
